
knp_paginator:
    page_range: 5                       # pager
    default_options:
        page_name: page                 # page
        sort_field_name: sort           # sort
        sort_direction_name: direction  # dir
        distinct: true                  # distinct
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'
