# Configuration du bundle de pagination
# Utilisé pour paginer les thèmes (5/page) et les discussions (10/page)

knp_paginator:
    page_range: 5                       # Nombre de pages à afficher
    default_options:
        page_name: page                 # Nom du paramètre GET
        sort_field_name: sort           # Nom du paramètre de tri
        sort_direction_name: direction  # Nom du paramètre de direction
        distinct: true                  # Résultats distincts
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'
