
twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'   # form
    globals:
        site_name: 'Forum'                  # global

when@test:
    twig:
        strict_variables: true
