
parameters:

services:
    _defaults:
        autowire: true      # auto
        autoconfigure: true # auto

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\UserChecker:
        tags:
            - { name: security.user_checker.main }
